version: '3.3'

services:
  user-service:
    container_name: users-service
    build:
      context: ./users-service
      dockerfile: Dockerfile-dev
    volumes:
      - './users-service:/usr/src/app'
    ports:
      - 5001:500
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      